# Generated by Django 4.1.2 on 2023-06-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_scheduled_publish_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scheduled_publish',
        ),
    ]
