# Generated by Django 4.1.2 on 2023-06-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_post_scheduled_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_publish',
            field=models.DateTimeField(blank=True, help_text='Date and time to schedule the post for publishing', null=True),
        ),
    ]
