# Generated by Django 4.1.2 on 2023-06-20 08:44

import backend.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_post_scheduled_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Choose author for the post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Your blog post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('business', 'Business'), ('politics', 'Politics'), ('art', 'Art')], default='sales', help_text='Category for the post', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to make the post featured'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Image should be less than 500MB', null=True, upload_to='images/', validators=[backend.models.ImageSizeValidator(max_size_mb=0.5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='readTime',
            field=models.IntegerField(help_text='Read time for the post', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Blog post title', max_length=200),
        ),
    ]
